# Generated by Django 5.2.14 on 2026-06-01 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_whatsapp_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'Paiement en attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('MAINTENANCE', 'Maintenance')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
