# Generated by Django 5.2.14 on 2026-06-08 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_modelavage_consigne_securite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='closing_time',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Heure de fermeture'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name="Heure d'ouverture"),
        ),
    ]
