# Generated by Django 5.2.14 on 2026-06-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_establishment_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelavage',
            name='consigne_securite_ar',
            field=models.TextField(blank=True, default='', verbose_name='Consigne de sécurité (arabe)'),
        ),
        migrations.AddField(
            model_name='modelavage',
            name='message_guide_ar',
            field=models.TextField(blank=True, default='', verbose_name='Pourquoi choisir ce mode (arabe)'),
        ),
        migrations.AddField(
            model_name='modelavage',
            name='nom_ar',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nom (arabe)'),
        ),
        migrations.AddField(
            model_name='modelavage',
            name='textiles_interdits_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='Textiles à éviter / interdits (arabe)'),
        ),
        migrations.AddField(
            model_name='modelavage',
            name='types_vetements_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='Types de vêtements (arabe)'),
        ),
    ]
